name: classic-launch
version: current
summary: A launcher part that sets the adapter for snaps in classic confinement
description: |
  This remote part provide necessary runtime changes to deal with several problems in a snap with classic confinement.

  Refer the following snapcraft forum topic for more info:

      The classic-launch Remote Part - doc - snapcraft.io
      https://forum.snapcraft.io/t/the-classic-launch-remote-part/9053

grade: stable
confinement: strict

parts:
  classic-launch:
    plugin: dump
    source: launchers
    organize:
      '*': bin/
    stage:
    - -README.*
